### ISSUE TITLE
[Bug] vercel.json 中对于图片的重定向配置失效？

### ISSUE THREAD

**Issue by 006lp** [FreeNowOrg/PixivNow#108]
我尝试通过Vercel部署，发现无法显示图片，按照Readme所写替换为自己的反代地址，但是仍然被定向至i.pixiv.net.
![无标题](https://github.com/FreeNowOrg/PixivNow/assets/144674902/790ddf3c-8b09-42f0-9d92-de3905bf3918)
![无标题2](https://github.com/FreeNowOrg/PixivNow/assets/144674902/e1dbd3ed-181c-4b27-afe9-8023724e1492)

我的反代应该没有问题，因为当我将域名替换成我的后能够显示出来。
![无标题3](https://github.com/FreeNowOrg/PixivNow/assets/144674902/2119b34c-e580-4552-b696-47354675982c)
麻烦提供一下解决办法谢谢

**Comment by Hoshino-Yumetsuki** [comment]
> 我尝试通过Vercel部署，发现无法显示图片，按照Readme所写替换为自己的反代地址，但是仍然被定向至i.pixiv.net. ![无标题](https://private-user-images.githubusercontent.com/144674902/320219835-790ddf3c-8b09-42f0-9d92-de3905bf3918.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjcwMzIsIm5iZiI6MTcxMzQyNjczMiwicGF0aCI6Ii8xNDQ2NzQ5MDIvMzIwMjE5ODM1LTc5MGRkZjNjLThiMDktNDJmMC05ZDkyLWRlMzkwNWJmMzkxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNzUyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTFlMjA3NTAyNGE3NmU0ODIzY2E1OGRlNzBmYWFkNjA0Y2M2MTg0YWJjZTg1MmFmNTA2ZDYzMWZlODgyOGNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vc6KJ9U3BT50B32ysGRrnqUCoog-nkRcbPT1KUKxIYM) ![无标题2](https://private-user-images.githubusercontent.com/144674902/320219842-e1dbd3ed-181c-4b27-afe9-8023724e1492.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjcwMzIsIm5iZiI6MTcxMzQyNjczMiwicGF0aCI6Ii8xNDQ2NzQ5MDIvMzIwMjE5ODQyLWUxZGJkM2VkLTE4MWMtNGIyNy1hZmU5LTgwMjM3MjRlMTQ5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNzUyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2I3ZGM1MmRjMjM2ZTAzODM4NTE1YjFlNDY2YTcwMjZjODA3ZDJlMTU3ZWI1YWEzYmNkZDc0YjdmMzUwYTM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BfORbcnUFWiyFe6khUsVZJSiTSxOzLMcMwKvCOMvz4I)
> 
> 我的反代应该没有问题，因为当我将域名替换成我的后能够显示出来。 ![无标题3](https://private-user-images.githubusercontent.com/144674902/320219864-2119b34c-e580-4552-b696-47354675982c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjcwMzIsIm5iZiI6MTcxMzQyNjczMiwicGF0aCI6Ii8xNDQ2NzQ5MDIvMzIwMjE5ODY0LTIxMTliMzRjLWU1ODAtNDU1Mi1iNjk2LTQ3MzU0Njc1OTgyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNzUyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDdmZjZiN2I3ZWFmYjE1MTZkNjI5YWJjOGZiNGY2N2JmNDA0YTUwYjYyMWE3ZWY0YjdmZGI1MGRkNDhhZWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AvNx76kMPaDnLrlN98e-A8WbZRLIagAKiT-MExfDK5Y) 麻烦提供一下解决办法谢谢

现在的反代配置方法已经从更改vercel.json变为从vercel的环境变量`VITE_PXIMG_BASEURL_I`传递

**Comment by AlPha5130** [comment]
相关说明已在readme中更新（ #109 ）
