### ISSUE TITLE
pximg.wjghj.cn 代理返回 421，无法加载图片

### ISSUE THREAD

**Issue by asadahimeka** [FreeNowOrg/PixivNow#127]
RT，貌似通过 CNAME 代理行不通了，`i.pximg.net` 好像检测了 `Host` 头

![image](https://github.com/user-attachments/assets/ba577037-857a-436b-b264-8f9308e37afb)
![image](https://github.com/user-attachments/assets/899706b1-2f90-44d0-879c-2944c9133f0c)

**Comment by dragon-fish** [comment]
暂时没有精力处理这个问题，之前有试过 cf worker，次数撑不住
如果有更好的解决方法欢迎同步

**Comment by dragon-fish** [comment]
我曾在2024年3月5日向 pixiv.cat 的作者发去了一封邮件，表明了希望在 pixiv.js.org 中使用他的服务，但是并没有收到回信

**Comment by asadahimeka** [comment]
目前在免费环境大流量场景下确实没找到什么好办法，之前曾经想过使用域前置直连加载，但需要 Tampermonkey / Native Request 支持才能突破浏览器限制，对于用户来说成本略高
