### ISSUE TITLE
关于登录时403错误

### ISSUE THREAD

**Issue by Hanze-C** [FreeNowOrg/PixivNow#144]
PixivNow登录时出现403错误
根据Pixeval与PixEZ的issue，该错误可能来自于pixiv服务器
[Pixeval #542](https://github.com/Pixeval/Pixeval/issues/542)
[PixEZ #845](https://github.com/Notsfsssf/pixez-flutter/issues/845)
[PixivShaft #661](https://github.com/CeuiLiSA/Pixiv-Shaft/issues/661)

**Comment by Hanze-C** [comment]
> PixivNow登录时出现403错误 根据Pixeval与PixEZ的issue，该错误可能来自于pixiv服务器 [Pixeval #542](https://github.com/Pixeval/Pixeval/issues/542) [PixEZ #845](https://github.com/Notsfsssf/pixez-flutter/issues/845) [PixivShaft #661](https://github.com/CeuiLiSA/Pixiv-Shaft/issues/661)

**Comment by liugyuuu** [comment]
<img width="631" alt="Desktop Screenshot 2024 12 13 - 23 33 22 53" src="https://github.com/user-attachments/assets/281e838d-d64a-424d-918f-4b1ad797f039" />
[2024-12-13 23.log](https://github.com/user-attachments/files/18128290/2024-12-13.23.log)

已经使用了作者的settings文件

**Comment by 006lp** [comment]
所以想问一下这个问题在PixivNow上该怎么解决呢
