### ISSUE TITLE
部署是遇到的问题

### ISSUE THREAD

**Issue by ObcbO** [FreeNowOrg/PixivNow#16]
上次修复后不是404了，这次却变成了

<https://pixiv.obcbo.tk>

![Screenshot_20220312-125609_Via](https://user-images.githubusercontent.com/49872497/158004350-b6757da7-b74c-44f2-a2b8-545f42baf2af.png)

**Comment by Dragon-Fish** [comment]
难以修复

参见: https://github.com/FreeNowOrg/PixivNow/pull/17#issuecomment-1065832278

**Comment by ObcbO** [comment]
> 难以修复
> 
> 参见: [#17 (comment)](https://github.com/FreeNowOrg/PixivNow/pull/17#issuecomment-1065832278)

![Screenshot_20220313-102449_Via](https://user-images.githubusercontent.com/49872497/158042180-d42e948c-cebd-4c6e-9b62-1315168732a4.png)
这样设置又回到404界面了

**Comment by Dragon-Fish** [comment]
你这设置的和我图里的也不一样，选vue

**Comment by ObcbO** [comment]
> 你这设置的和我图里的也不一样，选vue

问题解决了 谢谢大佬
