### ISSUE TITLE
Only 24 images of an artist are shown

### ISSUE THREAD

**Issue by KrischnaGabriel** [FreeNowOrg/PixivNow#23]
Currently when visiting the pixiv.js.org website and browsing trough the posts of an artist, only 24 max are shown and here's no option to show more.

**Comment by AlPha5130** [comment]
The author @Dragon-Fish initially did not implement pagination, so there are only 24 images shown.

**Comment by dragon-fish** [comment]
If I have enough free time. Maybe I will try to make it works in the 2023 Chinese New Year.

**Comment by dragon-fish** [comment]
This is a reminder for developers:

**Get all illust ids by user**

```http
GET /ajax/user/32338232/profile/all
```

```ts
const illustIdsByUser = Object.keys(response.body.illusts)
```

**Get illusts details by ids**

```
GET /ajax/user/32338232/profile/illusts?ids[]=<illust_id...>&work_category=illustManga&is_first_page=1
```

e.g. https://www.pixiv.net/ajax/user/32338232/profile/illusts?ids%5B%5D=104385147&ids%5B%5D=98550690&ids%5B%5D=97522118&ids%5B%5D=97444115&ids%5B%5D=94928692&ids%5B%5D=94928661&ids%5B%5D=94928596&ids%5B%5D=93159578&ids%5B%5D=89719747&ids%5B%5D=89719674&ids%5B%5D=86468782&ids%5B%5D=71888385&ids%5B%5D=71804241&ids%5B%5D=71804123&ids%5B%5D=71803979&work_category=illustManga&is_first_page=1
