### ISSUE TITLE
构建过程出现error

### ISSUE THREAD

**Issue by tomomuy** [FreeNowOrg/PixivNow#25]
构建设置：
![image](https://user-images.githubusercontent.com/116566664/205417425-da25afbd-f6ce-448c-bbfc-5ffa2b46efbe.png)
错误日志：
![image](https://user-images.githubusercontent.com/116566664/205417458-51180fa5-ade8-4c58-a55c-7c169c52737e.png)
![image](https://user-images.githubusercontent.com/116566664/205417463-913b5f07-6faa-4034-bf67-2ddc8a9b510a.png)
![image](https://user-images.githubusercontent.com/116566664/205417469-0e9f6114-3b26-47db-9c34-b0ceeccb469d.png)
出现的问题：
![image](https://user-images.githubusercontent.com/116566664/205417482-e68f572f-7202-4092-8860-b4ce94a1d121.png)
![image](https://user-images.githubusercontent.com/116566664/205417501-a12c24a8-e8e1-4eb7-895b-8730750b76e8.png)

**Comment by asadahimeka** [comment]
我是这么改的，你可以照着试试看

api/illust/random.ts [第 25 行](https://github.com/FreeNowOrg/PixivNow/blob/master/api/illust/random.ts#L25) 修改为 ( 1 和 18 加上引号 )
```js
max: isImage ? '1' : req.query.max || '18',
```

api/http.ts [第 20 行](https://github.com/FreeNowOrg/PixivNow/blob/master/api/http.ts#L20) 改为
```js
const e = err as any
res.status(e?.response?.status || 500).send(e?.response?.data || e)
```

然后在 `api` 目录下新建一个 `_shims.d.ts` 文件，内容如下
```ts
declare module 'camelcase-object-deep';
```

**Comment by tomomuy** [comment]
> 我是这么改的，你可以照着试试看
> 
> api/illust/random.ts[第 25 行](https://github.com/FreeNowOrg/PixivNow/blob/master/api/illust/random.ts#L25)修改为 （ 1 和 18 加上引号 ）
> 
> ```js
> max: isImage ? '1' : req.query.max || '18',
> ```
> 
> api/http.ts [第 20 行](https://github.com/FreeNowOrg/PixivNow/blob/master/api/http.ts#L20) 改为
> 
> ```js
> const e = err as any
> res.status(e?.response?.status || 500).send(e?.response?.data || e)
> ```
> 
> 然后在 目录下新建一个 文件，内容如下`api``_shims.d.ts`
> 
> ```ts
> declare module 'camelcase-object-deep';
> ```
> 
> API 调用 403 的问题需要加一个环境变量指定一下黑名单 UA 如
> 
> ```
> UA_BLACKLIST=["googlebot"]
> ```
> 
> 或者直接修改 api/utils.ts [第 101 行](https://github.com/FreeNowOrg/PixivNow/blob/master/api/utils.ts#L101)
> 
> ```js
> const { UA_BLACKLIST = '["googlebot"]' } = process.env
> ```

感谢大佬，虽然还是会报找不到 `camelcase-object-deep`  模块的错误，但是部署后api已经可以正常使用了
