### ISSUE TITLE
在部署之后登陆或者搜索出现Unexpected token 'A', "A server e"... is not valid JSON

### ISSUE THREAD

**Issue by Polaris-Ye** [FreeNowOrg/PixivNow#30]
![image](https://user-images.githubusercontent.com/66023444/221508786-83a38038-6e0e-4b1a-9c6a-79babe4e4fe9.png)
如图

**Comment by dragon-fish** [comment]
vercel serverless functions 的行为变了，现在还没搞清楚要怎么修

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by Polaris-Ye** [comment]
谢谢谢谢，辛苦了，没想到我提issue这么快就回复好感动

**Comment by Polaris-Ye** [comment]
咱们有Q群吗我加一个方便随时观望动态可以吗

**Comment by Polaris-Ye** [comment]
太巧了，我就是使用koishi搭建setu插件，在哪里能联系到您吗

**Comment by dragon-fish** [comment]
> 咱们有Q群吗我加一个方便随时观望动态可以吗

没有专门为这个项目建的QQ群，毕竟主要开发者就两个人。所以一般都是借用我的另一个开源项目的群聊PixivNow
