### ISSUE TITLE
drop `@fortawesome/*`

### ISSUE THREAD

**Issue by dragon-fish** [FreeNowOrg/PixivNow#33]
https://github.com/FreeNowOrg/PixivNow/blob/4b855655495fda2b78b3daf5865bad1cd9e57f25/src/main.ts#L21-L27

任选一种方案皆可

- 换用 `@vicons/fa`
- 不换依赖，改成按需导入
- 也可以找其他方案，比如换成 auto import（好像 NaiveUI 社区有人提出了 @vicons/fa 的 auto import 的脚本）

目前全量导入 fontawesome-svg-core 导致入口文件非常巨大，流量有点扛不住

**Comment by AlPha5130** [comment]
目前以使用[unplugin-icons](https://github.com/antfu/unplugin-icons)的方式解决了全量导入icons的问题，暂时没发现什么问题。
