### ISSUE TITLE
use `http-only` for token cookie

### ISSUE THREAD

**Issue by dragon-fish** [FreeNowOrg/PixivNow#34]
虽然要求用户自己提供 cookie 本身就已经够不安全了，但我们还是可以让 cookie 保存的稍微安全一点

（这个功能难道不应该先给 BlogNow 做吗 kora）

**Comment by AlPha5130** [comment]
要做的话，因为js读不到token了，所以登录认证的部分要重新实现

**Comment by dragon-fish** [comment]
对，需要占用一个函数接口来实现登入和登出

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).
