### ISSUE TITLE
api相关错误及使用cookie登陆时的错误

### ISSUE THREAD

**Issue by ldcivan** [FreeNowOrg/PixivNow#43]
设置Pixiv令牌时，在输入PHPSESSID并提交表单后出现了Request failed with status code 500的报错。无论是否有使用VPN都会出现此报错。

**Comment by ldcivan** [comment]
> 设置Pixiv令牌时，在输入PHPSESSID并提交表单后出现了Request failed with status code 500的报错。无论是否有使用VPN都会出现此报错。

此外，pixiv now下的所有api均会返回500错误，想请教一下原因？

**Comment by AlPha5130** [comment]
请问您是在pixiv.js.org上遇到的问题还是自己部署时遇到的问题？

**Comment by ldcivan** [comment]
> 请问您是在pixiv.js.org上遇到的问题还是自己部署时遇到的问题？

是自行部署时的问题，仅替换了pximg镜像源，其余未作任何更改T T

**Comment by AlPha5130** [comment]
能否提供您在运行时报错的日志

**Comment by AlPha5130** [comment]
> 此外，api下的random与user功能都会返回500错误。比如使用random功能时，vercel中会有类似这样的报错：
> `Error: Cannot find module '/var/task/api/http' imported from /var/task/api/random.js`
> 想请教一下原因？

可参考 https://github.com/orgs/vercel/discussions/1225

**Comment by ldcivan** [comment]
> 能否提供您在运行时报错的日志

1.500错误页

<img width="520" alt="image" src="https://github.com/FreeNowOrg/PixivNow/assets/69411867/2b604a15-e463-4875-9f4d-26f84a2037a8">

2.运行log
<pre>
Error: Cannot find module '/var/task/api/http' imported from /var/task/api/user.js
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:331:11)
    at moduleResolve (node:internal/modules/esm/resolve:994:10)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:938:12)
    at defaultResolve (node:internal/modules/esm/resolve:1202:79)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
RequestId: 183fad34-df42-4791-a3a9-a97441e115c1 Error: Runtime exited with error: exit status 1
Runtime.ExitError
</pre>

感谢，我也去看看那篇参考

**Comment by AlPha5130** [comment]
简单来说就是node按ESM导入文件时必须加上.js的后缀
但是本仓库的维护者很神奇地~~靠不升级vercel版本~~解决了这个问题

**Comment by ldcivan** [comment]
> 简单来说就是node按ESM导入文件时必须加上.js的后缀 但是本仓库的维护者很神奇地~靠不升级vercel版本~解决了这个问题

所以这个问题未来会在仓库修复嘛，我感觉没有任何能力自己把他改好（主要是我真不懂这个T T）

**Comment by ldcivan** [comment]
将`/api/random.ts` 中的 `import { ajax } from './http'` 改成 `import { ajax } from './http.js'`

以及，将`/api/user.ts` 中的 `import { ajax, replaceUrlInObject } from './http'` 改成 `import { ajax, replaceUrlInObject } from './http.js'`

即可基本解决api失效的问题

另外提一嘴，现在我这边似乎无法直接访问如同`example.com/artworks/84590400`这样的页面，且刷新一个已经正常加载了的作品页面也会出错（均返回404），但`pixiv.js.org`上确实可以直接访问的。不知道是什么原因呢？

不过这是题外话了，也不是啥大事，我先结案了，谢谢了哈

**Comment by dragon-fish** [comment]
这是一个路由的bug，一直没修它，你可以另起一个issue以防我忘记

**Comment by ldcivan** [comment]
> 这是一个路由的bug，一直没修它，你可以另起一个issue以防我忘记

我在一个[远古issue](https://github.com/FreeNowOrg/PixivNow/pull/17#issuecomment-1065832278)找到了您给出的相关解决方案，不过似乎当时您自己把[提这个bug的issue](https://github.com/FreeNowOrg/PixivNow/issues/16)给close as complete了（笑）

**Comment by dragon-fish** [comment]
那不修了，能用就行

**Comment by dragon-fish** [comment]
这个issue所描述的问题是**应该**被解决的，官仓目前采取的降级Vercel CLI手段不是一个长久之计
