### ISSUE TITLE
路由bug：访问/artwork/*等页面可能会返回404

### ISSUE THREAD

**Issue by ldcivan** [FreeNowOrg/PixivNow#44]
以artwork页面为例，当用户直接在地址栏输入如`example.com/artwork/123456`的地址时、或是刷新这样的地址时，vercel会返回404页面。user，search等页面同理。

**Comment by dragon-fish** [comment]
**仅作记录**

尝试在 vercel.json 的 `rewrites` 里添加以下内容：

```json
    {
      "source": "/(.*)",
      "destination": "/index.html"
    }
```

导致本地测试时，所有请求都被重定向到 index.html，诸如 `http://localhost:3000/@vite/client` 的请求会得到一个 404

**Comment by dragon-fish** [comment]
不想修了，摆烂：

1. vue-router 改用 `createWebHashHistory` （但这不够酷！）
2. vercel 部署的时候选择 Vue.js 预设
