### ISSUE TITLE
手机端ui适配问题

### ISSUE THREAD

**Issue by tang-bai** [FreeNowOrg/PixivNow#47]
在手机端网页访问的时候图片只会显示一列,是否可以适配成2列
![_61134fbce2519c02c06b7e6b036affc0_-866537205_Screenshot_2023-09-10-23-04-44-155_com quark browser](https://github.com/FreeNowOrg/PixivNow/assets/71223830/b880b4ee-1990-461e-8aac-c2f6b6418e2e)
比如这样子
![image](https://github.com/FreeNowOrg/PixivNow/assets/71223830/19917dc2-2adf-49a4-aeca-39e526313125)

**Comment by dragon-fish** [comment]
![d8119e52587ae35e72e8880087745607](https://github.com/FreeNowOrg/PixivNow/assets/44761872/7c9b501e-c343-4d32-9eb4-4b9d671e78ea)

怪事，我记得最少是两列

**Comment by dragon-fish** [comment]
![image](https://github.com/FreeNowOrg/PixivNow/assets/44761872/2b29ec3d-e224-42ab-9cbc-3177b134465f)
![image](https://github.com/FreeNowOrg/PixivNow/assets/44761872/98e29a36-9dad-49ef-8cb6-c69e008f8712)
It works on my machine

你是什么设备

**Comment by tang-bai** [comment]
手机是小米13pro
测试浏览器为手机端的edge和小米自带浏览器以下是版本信息
![4a84f6e3cb3771a50c036664522ce42](https://github.com/FreeNowOrg/PixivNow/assets/71223830/ae9d64e4-ad96-4467-bc5f-73a4ee4ea56b)
![456045129ded067c70628bf5b21522f](https://github.com/FreeNowOrg/PixivNow/assets/71223830/5b33ad2d-37a8-479d-b4b2-6de82570fa1c)

**Comment by tang-bai** [comment]
浏览器选择对应的应该是移动L
![image](https://github.com/FreeNowOrg/PixivNow/assets/71223830/38ab2cf9-91d9-4b44-99c8-90fab96d4e60)

**Comment by AlPha5130** [comment]
我大概知道了，应该是图片的宽度设置不合适
