### ISSUE TITLE
［FEAT］支持使用mongodb保存cookies让用户无需反复登录

### ISSUE THREAD

**Issue by Anjiurine** [FreeNowOrg/PixivNow#61]
希望后续可以使用自定义密码+mongodb的形式来读取在数据库中保存的cookies，这样就不用在每一个登录地点单独配置cookies了

**Comment by dragon-fish** [comment]
不太想支持该功能。
1. cookie本身就会变化，导致登录状态失效
2. 如果做了登录系统，网站的性质会有一些微妙的变化，hack掉pixiv的登录系统性质会更糟糕
3. 我的MongoDB Atlas快满了

**Comment by Anjiurine** [comment]
> 不太想支持该功能。
> 
> 1. cookie本身就会变化，导致登录状态失效
> 2. 如果做了登录系统，网站的性质会有一些微妙的变化，hack掉pixiv的登录系统性质会更糟糕
> 3. 我的MongoDB Atlas快满了

emmm，主要我这边是自己部署的，应该可以当作一个可选功能（

**Comment by Anjiurine** [comment]
这个功能应该是当作一个中间保存令牌的功能，似乎性质也不算hack掉登陆系统，其次mongodb免费账户可以创建很多个mongodb，如果是自己部署的话，让用户在部署的时候自己输入mongodb uri就好了

**Comment by Anjiurine** [comment]
> 这个功能应该是当作一个中间保存令牌的功能，作用也**仅仅是负责在用户输入cookies后保存令牌**，似乎性质也不算hack掉登陆系统，其次mongodb免费账户可以创建很多个mongodb，如果是自己部署的话，让用户在部署的时候自己输入mongodb uri就好了
