### ISSUE TITLE
[提问] 如何在自己电脑上部署本项目？——更便宜的解决方案

### ISSUE THREAD

**Issue by hmjz100** [FreeNowOrg/PixivNow#64]
电脑有改别人废稿做出的[NginxPixiv反代](https://github.com/hmjz100/Super-Nginx)，可以直接开Pixiv（首页较慢），也试着编译过本项目为html（因为不太会Vue，所以以做出api跳转到本地反代失败而告终），因为觉得本项目<s>色图</s>(bushi)推荐机制**比原Pixiv更好**，而且**加载速度也更快**，所以想在本地部署一个<s>（有时间的话可能会做出侧栏的插画页面？）</s>
### 总体来说，就是想让本项目做出本地版，用户通过反代自行部署到机器上（这样也是一种更便宜的解决方案，还不用与某网络环境斗智斗勇）

**Comment by dragon-fish** [comment]
不用编译，本来就可以跑在本地

```sh
pnpm serve
```

不然你以为咱是怎么开发的，颅内渲染吗（×

**Comment by hmjz100** [comment]
不好意思说错了，项目确实可以跑在本地，但```npm run serve```在本项目的package.json指定的是运行```vercel dev```（这让我走了不少弯路），后来我终于摸索出来了本地运行的方法
```
cnpm install
npm run build
cd dist
vite
```
可是新的问题来了，网站是跑出来了，**该怎么配置才能使```localhost:5173/~/common/images/no_profile.png```跳转到```s.pximg.net/common/images/no_profile.png```**，（总不能我一个个去替换吧）

**Comment by dragon-fish** [comment]
我已经告诉你了跑在本地的方法是 `pnpm serve`，不知道你为什么要自己瞎折腾。

本项目当下跑在 master 的代码（路由和后端中间件之类的）是基于 @vercel/node 实现的。

如果你认为这很麻烦，可以等我们即将推送的基于 nuxt 的重构。

**Comment by dragon-fish** [comment]
https://github.com/FreeNowOrg/PixivNow/assets/44761872/a134f3dc-aefd-4a58-b579-b466f6dd8b2a

**Comment by hmjz100** [comment]
好(╯▽╰)，那我还是等等吧（不想注册vercel账号）
