### ISSUE TITLE
[Bug] 在首页搜索作品后，搜索结果中的画师id和作品id相同导致的路径错误

### ISSUE THREAD

**Issue by Anjiurine** [FreeNowOrg/PixivNow#66]
在首页搜索作品后，搜索结果中的画师id和作品id相同，导致直接从搜索结果界面中点击画师头像无法直接进入画师主页，出现404错误
![image](https://github.com/FreeNowOrg/PixivNow/assets/147403913/b128931c-590b-4fdd-9e35-8b4acab9c5bc)

**Comment by dragon-fish** [comment]
https://github.com/FreeNowOrg/PixivNow/blob/fb94a366ca6642934b010472ea2567bd0993b375/src/components/ArtworksList/ArtworkLargeCard.vue#L28

确实写错了，你想水pr吗

**Comment by Anjiurine** [comment]
> https://github.com/FreeNowOrg/PixivNow/blob/fb94a366ca6642934b010472ea2567bd0993b375/src/components/ArtworksList/ArtworkLargeCard.vue#L28
> 
> 确实写错了，你想水pr吗

好啊（

**Comment by Anjiurine** [comment]
> https://github.com/FreeNowOrg/PixivNow/blob/fb94a366ca6642934b010472ea2567bd0993b375/src/components/ArtworksList/ArtworkLargeCard.vue#L28
> 
> 确实写错了，你想水pr吗

vue修不明白，等你修好罢（

**Comment by asadahimeka** [comment]
昨日重现 [#24](https://github.com/FreeNowOrg/PixivNow/pull/24)
之前提过的 PR 不知道为啥丢了 <img src="https://user-images.githubusercontent.com/31837214/214237746-f3a5420f-9f2e-4eff-b5a4-ce2cb483a6c2.png" width=30>
