### ISSUE TITLE
[FEAT] 在使用random接口时支持从查询字符串中提供cookie

### ISSUE THREAD

**Issue by Anjiurine** [FreeNowOrg/PixivNow#76]
就像这样

```
https://<server_name>/api/illust/random?cookie=<cookie>
```

**Comment by dragon-fish** [comment]
我记得远古版本是可以通过 `token` 查询参数传递 PHPSESSID 的，后来不知道为什么删掉了，可能是因为觉得不安全
请问为什么会有这种需求，什么场景迫使你无法传递 cookie 请求头？

**Comment by Anjiurine** [comment]
> 我记得远古版本是可以通过 `token` 查询参数传递 PHPSESSID 的，后来不知道为什么删掉了，可能是因为觉得不安全 请问为什么会有这种需求，什么场景迫使你无法传递 cookie 请求头？

并没有迫使之类的，主要是cookie传递较为麻烦，所以想直接通过查询字符串传递token

**Comment by dragon-fish** [comment]
尽量还是用请求头传递 token 吧，不然的话风险还是挺高的，访问日志里都能直接看到明文的 token
