### ISSUE TITLE
在使用环境变量传递pixiv图片反代后，主页的大图依旧会按照vercel.json的重定向将图片链接重定向到json中的链接

### ISSUE THREAD

**Issue by Hoshino-Yumetsuki** [FreeNowOrg/PixivNow#92]
![image](https://github.com/FreeNowOrg/PixivNow/assets/147403913/e1dc5ba8-7329-43ca-9fca-1c9724b1100c)

**Comment by AlPha5130** [comment]
@dragon-fish

**Comment by dragon-fish** [comment]
https://github.com/FreeNowOrg/PixivNow/blob/83b8cf01b49808f50cbde89243fe1f3df436c932/api/random.ts#L32-L38

嘶……

**Comment by Anjiurine** [comment]
> https://github.com/FreeNowOrg/PixivNow/blob/83b8cf01b49808f50cbde89243fe1f3df436c932/api/random.ts#L32-L38
> 
> 嘶……

我的建议是，直接把http.ts的部分插入到这玩意儿里面，因为我之前在修的时候发现src不能读取到api文件夹的内容
